name: Builds

on: [push, pull_request]

jobs:
  fmt:
    runs-on: windows-latest
    name: fmt
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up rust
        run: rustup default stable

      - name: cargo fmt
        run: cargo fmt --check

  clippy:
    name: clippy
    runs-on: windows-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up rust
        run: rustup default stable

      - name: cargo clippy
        env:
          RUSTFLAGS: "-Dwarnings"
        run: cargo clippy

  build:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
    runs-on: ${{ matrix.os }}
    name: build & test (${{ matrix.os }})
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up rust
        run: rustup default stable

      - name: cargo test
        run: cargo test

      - name: cargo build
        run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshot (${{ matrix.os }})
          path: |
            target/release/snapshot.dll
            target/release/snapshot.pdb